import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { 
  faUser, 
  faEdit, 
  faTrash, 
  faPlus,
  faPlusCircle,
  faUsers,
  faHome,
  faCog,
  faLock,
  faBars,
  faCalendar,
  faCheck,
  faFileAlt,
  faBell,
  faWrench,
  faSignOutAlt,
  faList,
  faChartBar,
  faQuestionCircle,
  faPlug,
  faSearch,
  faMinus,
  faUserShield,
  faDiagramProject,
  faPaperPlane,
  faTableList,
  faRightToBracket,
  faClockRotateLeft,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faUser, 
  faEdit, 
  faTrash, 
  faPlus,
  faPlusCircle,
  faUsers,
  faHome,
  faCog,
  faLock,
  faBars,
  faCalendar,
  faCheck,
  faFileAlt,
  faBell,
  faWrench,
  faSignOutAlt,
  faList,
  faChartBar,
  faQuestionCircle,
  faPlug,
  faSearch,
  faMinus,
  faUserShield,
  faDiagramProject,
  faPaperPlane,
  faTableList,
  faRightToBracket,
  faClockRotateLeft,
)

export default FontAwesomeIcon 